.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-VENDOR" "1" "February 2016" "" "Git Vendor"
.
.SH "NAME"
\fBgit\-vendor\fR \- manage vendored dependency subtrees
.
.SH "SYNOPSIS"
\fBgit\-vendor add [\-\-prefix <dir>] <name> <repository> [<ref>]\fR
.
.P
\fBgit\-vendor list [<name>]\fR
.
.P
\fBgit\-vendor remove <name>\fR
.
.P
\fBgit\-vendor update <name> [<ref>]\fR
.
.P
\fBgit\-vendor upstream <name> [<ref>]\fR
.
.SH "DESCRIPTION"
Manage any repository dependencies with \fBgit\-subtree\fR\.
.
.P
\fBgit\-vendor\fR follows the same vendoring pattern that is used in the Go community\. Dependencies are stored under \fBvendor/<repository_uri>\fR\. For example, the dependency of \fBhttps://github\.com/brettlangdon/forge\.git\fR will be stored under \fBvendor/github\.com/brettlangdon/forge\fR by default\.
.
.P
\fBgit\-vendor\fR is unable to \fBlist\fR, \fBupdate\fR or \fBupstream\fR any dependencies it has not added, the reason is that \fBgit\-vendor\fR adds special commit messages so that it can track existing dependencies\.
.
.SH "COMMANDS"
add [\-\-prefix <dir>] <name> <repository> [<ref>]
.
.P
Add a new vendored dependency
.
.P
list [<name>]
.
.P
List all existing vendored dependencies and their current version\. Limit show dependency to \fB<name>\fR if provided\.
.
.P
remove <name>
.
.P
Remove the named vendored dependency\.
.
.P
update <dir> <ref>
.
.P
Update the vendored dependency to a different version\.
.
.P
upstream <dir> <ref>
.
.P
Push the vendored dependency changes to the source repository\.
.
.SH "OPTIONS"
\-\-prefix <dir>
.
.P
Directory to pull dependencies in under (e\.g\. \fBvendor\fR or \fBthird_party\fR, etc)\. [default: \fBvendor\fR]
.
.P
<name>
.
.P
A name to provide the vendored dependency to use when listing/updating\.
.
.P
<repository>
.
.P
The repository url to vendor\. e\.g\. \fBhttps://github\.com/<username>/<repo\-name>\fR (supports \fBhttp://\fR, \fBhttps://\fR \fBgit://\fR and \fBgit@\fR protocols)\.
.
.P
<ref>
.
.P
The ref to vendor\. e\.g\. \fBmaster\fR, \fBv1\.0\.2\fR, etc\. [default: \fBmaster\fR]
.
.SH "EXAMPLES"
Adding a new dependency at a specific git tagged version:
.
.IP "" 4
.
.nf

$ git vendor add forge https://github\.com/brettlangdon/forge v0\.1\.4
.
.fi
.
.IP "" 0
.
.P
Adding a new dependency under a different directory than \fBvendor/\fR:
.
.IP "" 4
.
.nf

$ git vendor add \-\-prefix third_party forge https://github\.com/brettlangdon/forge
.
.fi
.
.IP "" 0
.
.P
Updating an existing dependency to a specific git tagged version:
.
.IP "" 4
.
.nf

$ git vendor update forge  v0\.1\.7
.
.fi
.
.IP "" 0
.
.P
Updating a dependency to \fBmaster\fR:
.
.IP "" 4
.
.nf

$ git vendor update forge
.
.fi
.
.IP "" 0
.
.P
Upstream changes to the source repository to a (new) branch \fBmy_changes\fR:
.
.IP "" 4
.
.nf

$ git vendor upstream forge my_changes
.
.fi
.
.IP "" 0
.
.P
Upstream changes to the source repository to \fBmaster\fR:
.
.IP "" 4
.
.nf

$ git vendor upstream forge
.
.fi
.
.IP "" 0
.
.P
Upstream changes to another repository to a (new) branch \fBmy_changes\fR:
.
.IP "" 4
.
.nf

$ git vendor upstream forge my_changes --repo https://github.com/user/another.git
.
.fi
.
.IP "" 0
.
.P
Upstream changes to another repository to \fBmaster\fR:
.
.IP "" 4
.
.nf

$ git vendor upstream forge --repo https://github.com/user/another.git
.
.fi
.
.IP "" 0
.
.P
Removing a dependency:
.
.IP "" 4
.
.nf

$ git vendor remove forge
.
.fi
.
.IP "" 0
.
.P
List all existing dependencies:
.
.IP "" 4
.
.nf

$ git vendor list
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by Brett Langdon \fIme@brett\.is\fR
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/brettlangdon/git\-vendor/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/brettlangdon/git\-vendor\fR>
